name = "neckbreeze-store"
compatibility_date = "2024-12-01"
main = "worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "neckfan-db"
database_id = "51d08c6f-579c-4866-9964-b0a70f3f2601"
